/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mypipe.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UpdateMutation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UpdateMutation\",\"namespace\":\"mypipe.avro\",\"fields\":[{\"name\":\"database\",\"type\":\"string\"},{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"tableId\",\"type\":\"long\"},{\"name\":\"old_integers\",\"type\":{\"type\":\"map\",\"values\":\"int\"}},{\"name\":\"old_strings\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"old_longs\",\"type\":{\"type\":\"map\",\"values\":\"long\"}},{\"name\":\"new_integers\",\"type\":{\"type\":\"map\",\"values\":\"int\"}},{\"name\":\"new_strings\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"new_longs\",\"type\":{\"type\":\"map\",\"values\":\"long\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence database;
  @Deprecated public java.lang.CharSequence table;
  @Deprecated public long tableId;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Integer> old_integers;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> old_strings;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Long> old_longs;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Integer> new_integers;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> new_strings;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Long> new_longs;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public UpdateMutation() {}

  /**
   * All-args constructor.
   */
  public UpdateMutation(java.lang.CharSequence database, java.lang.CharSequence table, java.lang.Long tableId, java.util.Map<java.lang.CharSequence,java.lang.Integer> old_integers, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> old_strings, java.util.Map<java.lang.CharSequence,java.lang.Long> old_longs, java.util.Map<java.lang.CharSequence,java.lang.Integer> new_integers, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> new_strings, java.util.Map<java.lang.CharSequence,java.lang.Long> new_longs) {
    this.database = database;
    this.table = table;
    this.tableId = tableId;
    this.old_integers = old_integers;
    this.old_strings = old_strings;
    this.old_longs = old_longs;
    this.new_integers = new_integers;
    this.new_strings = new_strings;
    this.new_longs = new_longs;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return database;
    case 1: return table;
    case 2: return tableId;
    case 3: return old_integers;
    case 4: return old_strings;
    case 5: return old_longs;
    case 6: return new_integers;
    case 7: return new_strings;
    case 8: return new_longs;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: database = (java.lang.CharSequence)value$; break;
    case 1: table = (java.lang.CharSequence)value$; break;
    case 2: tableId = (java.lang.Long)value$; break;
    case 3: old_integers = (java.util.Map<java.lang.CharSequence,java.lang.Integer>)value$; break;
    case 4: old_strings = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 5: old_longs = (java.util.Map<java.lang.CharSequence,java.lang.Long>)value$; break;
    case 6: new_integers = (java.util.Map<java.lang.CharSequence,java.lang.Integer>)value$; break;
    case 7: new_strings = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 8: new_longs = (java.util.Map<java.lang.CharSequence,java.lang.Long>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'database' field.
   */
  public java.lang.CharSequence getDatabase() {
    return database;
  }

  /**
   * Sets the value of the 'database' field.
   * @param value the value to set.
   */
  public void setDatabase(java.lang.CharSequence value) {
    this.database = value;
  }

  /**
   * Gets the value of the 'table' field.
   */
  public java.lang.CharSequence getTable() {
    return table;
  }

  /**
   * Sets the value of the 'table' field.
   * @param value the value to set.
   */
  public void setTable(java.lang.CharSequence value) {
    this.table = value;
  }

  /**
   * Gets the value of the 'tableId' field.
   */
  public java.lang.Long getTableId() {
    return tableId;
  }

  /**
   * Sets the value of the 'tableId' field.
   * @param value the value to set.
   */
  public void setTableId(java.lang.Long value) {
    this.tableId = value;
  }

  /**
   * Gets the value of the 'old_integers' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Integer> getOldIntegers() {
    return old_integers;
  }

  /**
   * Sets the value of the 'old_integers' field.
   * @param value the value to set.
   */
  public void setOldIntegers(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
    this.old_integers = value;
  }

  /**
   * Gets the value of the 'old_strings' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getOldStrings() {
    return old_strings;
  }

  /**
   * Sets the value of the 'old_strings' field.
   * @param value the value to set.
   */
  public void setOldStrings(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.old_strings = value;
  }

  /**
   * Gets the value of the 'old_longs' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Long> getOldLongs() {
    return old_longs;
  }

  /**
   * Sets the value of the 'old_longs' field.
   * @param value the value to set.
   */
  public void setOldLongs(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
    this.old_longs = value;
  }

  /**
   * Gets the value of the 'new_integers' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Integer> getNewIntegers() {
    return new_integers;
  }

  /**
   * Sets the value of the 'new_integers' field.
   * @param value the value to set.
   */
  public void setNewIntegers(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
    this.new_integers = value;
  }

  /**
   * Gets the value of the 'new_strings' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getNewStrings() {
    return new_strings;
  }

  /**
   * Sets the value of the 'new_strings' field.
   * @param value the value to set.
   */
  public void setNewStrings(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.new_strings = value;
  }

  /**
   * Gets the value of the 'new_longs' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Long> getNewLongs() {
    return new_longs;
  }

  /**
   * Sets the value of the 'new_longs' field.
   * @param value the value to set.
   */
  public void setNewLongs(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
    this.new_longs = value;
  }

  /** Creates a new UpdateMutation RecordBuilder */
  public static mypipe.avro.UpdateMutation.Builder newBuilder() {
    return new mypipe.avro.UpdateMutation.Builder();
  }
  
  /** Creates a new UpdateMutation RecordBuilder by copying an existing Builder */
  public static mypipe.avro.UpdateMutation.Builder newBuilder(mypipe.avro.UpdateMutation.Builder other) {
    return new mypipe.avro.UpdateMutation.Builder(other);
  }
  
  /** Creates a new UpdateMutation RecordBuilder by copying an existing UpdateMutation instance */
  public static mypipe.avro.UpdateMutation.Builder newBuilder(mypipe.avro.UpdateMutation other) {
    return new mypipe.avro.UpdateMutation.Builder(other);
  }
  
  /**
   * RecordBuilder for UpdateMutation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UpdateMutation>
    implements org.apache.avro.data.RecordBuilder<UpdateMutation> {

    private java.lang.CharSequence database;
    private java.lang.CharSequence table;
    private long tableId;
    private java.util.Map<java.lang.CharSequence,java.lang.Integer> old_integers;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> old_strings;
    private java.util.Map<java.lang.CharSequence,java.lang.Long> old_longs;
    private java.util.Map<java.lang.CharSequence,java.lang.Integer> new_integers;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> new_strings;
    private java.util.Map<java.lang.CharSequence,java.lang.Long> new_longs;

    /** Creates a new Builder */
    private Builder() {
      super(mypipe.avro.UpdateMutation.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(mypipe.avro.UpdateMutation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.old_integers)) {
        this.old_integers = data().deepCopy(fields()[3].schema(), other.old_integers);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.old_strings)) {
        this.old_strings = data().deepCopy(fields()[4].schema(), other.old_strings);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.old_longs)) {
        this.old_longs = data().deepCopy(fields()[5].schema(), other.old_longs);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.new_integers)) {
        this.new_integers = data().deepCopy(fields()[6].schema(), other.new_integers);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.new_strings)) {
        this.new_strings = data().deepCopy(fields()[7].schema(), other.new_strings);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.new_longs)) {
        this.new_longs = data().deepCopy(fields()[8].schema(), other.new_longs);
        fieldSetFlags()[8] = true;
      }
    }
    
    /** Creates a Builder by copying an existing UpdateMutation instance */
    private Builder(mypipe.avro.UpdateMutation other) {
            super(mypipe.avro.UpdateMutation.SCHEMA$);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.old_integers)) {
        this.old_integers = data().deepCopy(fields()[3].schema(), other.old_integers);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.old_strings)) {
        this.old_strings = data().deepCopy(fields()[4].schema(), other.old_strings);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.old_longs)) {
        this.old_longs = data().deepCopy(fields()[5].schema(), other.old_longs);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.new_integers)) {
        this.new_integers = data().deepCopy(fields()[6].schema(), other.new_integers);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.new_strings)) {
        this.new_strings = data().deepCopy(fields()[7].schema(), other.new_strings);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.new_longs)) {
        this.new_longs = data().deepCopy(fields()[8].schema(), other.new_longs);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'database' field */
    public java.lang.CharSequence getDatabase() {
      return database;
    }
    
    /** Sets the value of the 'database' field */
    public mypipe.avro.UpdateMutation.Builder setDatabase(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.database = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'database' field has been set */
    public boolean hasDatabase() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'database' field */
    public mypipe.avro.UpdateMutation.Builder clearDatabase() {
      database = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'table' field */
    public java.lang.CharSequence getTable() {
      return table;
    }
    
    /** Sets the value of the 'table' field */
    public mypipe.avro.UpdateMutation.Builder setTable(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.table = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'table' field has been set */
    public boolean hasTable() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'table' field */
    public mypipe.avro.UpdateMutation.Builder clearTable() {
      table = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'tableId' field */
    public java.lang.Long getTableId() {
      return tableId;
    }
    
    /** Sets the value of the 'tableId' field */
    public mypipe.avro.UpdateMutation.Builder setTableId(long value) {
      validate(fields()[2], value);
      this.tableId = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'tableId' field has been set */
    public boolean hasTableId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'tableId' field */
    public mypipe.avro.UpdateMutation.Builder clearTableId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'old_integers' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Integer> getOldIntegers() {
      return old_integers;
    }
    
    /** Sets the value of the 'old_integers' field */
    public mypipe.avro.UpdateMutation.Builder setOldIntegers(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
      validate(fields()[3], value);
      this.old_integers = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'old_integers' field has been set */
    public boolean hasOldIntegers() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'old_integers' field */
    public mypipe.avro.UpdateMutation.Builder clearOldIntegers() {
      old_integers = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'old_strings' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getOldStrings() {
      return old_strings;
    }
    
    /** Sets the value of the 'old_strings' field */
    public mypipe.avro.UpdateMutation.Builder setOldStrings(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.old_strings = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'old_strings' field has been set */
    public boolean hasOldStrings() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'old_strings' field */
    public mypipe.avro.UpdateMutation.Builder clearOldStrings() {
      old_strings = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'old_longs' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Long> getOldLongs() {
      return old_longs;
    }
    
    /** Sets the value of the 'old_longs' field */
    public mypipe.avro.UpdateMutation.Builder setOldLongs(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
      validate(fields()[5], value);
      this.old_longs = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'old_longs' field has been set */
    public boolean hasOldLongs() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'old_longs' field */
    public mypipe.avro.UpdateMutation.Builder clearOldLongs() {
      old_longs = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'new_integers' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Integer> getNewIntegers() {
      return new_integers;
    }
    
    /** Sets the value of the 'new_integers' field */
    public mypipe.avro.UpdateMutation.Builder setNewIntegers(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
      validate(fields()[6], value);
      this.new_integers = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'new_integers' field has been set */
    public boolean hasNewIntegers() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'new_integers' field */
    public mypipe.avro.UpdateMutation.Builder clearNewIntegers() {
      new_integers = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'new_strings' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getNewStrings() {
      return new_strings;
    }
    
    /** Sets the value of the 'new_strings' field */
    public mypipe.avro.UpdateMutation.Builder setNewStrings(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[7], value);
      this.new_strings = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'new_strings' field has been set */
    public boolean hasNewStrings() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'new_strings' field */
    public mypipe.avro.UpdateMutation.Builder clearNewStrings() {
      new_strings = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'new_longs' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Long> getNewLongs() {
      return new_longs;
    }
    
    /** Sets the value of the 'new_longs' field */
    public mypipe.avro.UpdateMutation.Builder setNewLongs(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
      validate(fields()[8], value);
      this.new_longs = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'new_longs' field has been set */
    public boolean hasNewLongs() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'new_longs' field */
    public mypipe.avro.UpdateMutation.Builder clearNewLongs() {
      new_longs = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public UpdateMutation build() {
      try {
        UpdateMutation record = new UpdateMutation();
        record.database = fieldSetFlags()[0] ? this.database : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.table = fieldSetFlags()[1] ? this.table : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tableId = fieldSetFlags()[2] ? this.tableId : (java.lang.Long) defaultValue(fields()[2]);
        record.old_integers = fieldSetFlags()[3] ? this.old_integers : (java.util.Map<java.lang.CharSequence,java.lang.Integer>) defaultValue(fields()[3]);
        record.old_strings = fieldSetFlags()[4] ? this.old_strings : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[4]);
        record.old_longs = fieldSetFlags()[5] ? this.old_longs : (java.util.Map<java.lang.CharSequence,java.lang.Long>) defaultValue(fields()[5]);
        record.new_integers = fieldSetFlags()[6] ? this.new_integers : (java.util.Map<java.lang.CharSequence,java.lang.Integer>) defaultValue(fields()[6]);
        record.new_strings = fieldSetFlags()[7] ? this.new_strings : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[7]);
        record.new_longs = fieldSetFlags()[8] ? this.new_longs : (java.util.Map<java.lang.CharSequence,java.lang.Long>) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
